[package]
name = "kernel"
version = "0.1.0"
authors = ["Jan Katzer <jan@katzer.dev>"]
edition = "2018"

#[lib]
#crate-type = ["staticlib"]

[profile.dev]
#opt-level = 1

[dependencies]
cfg-if = "1.0.0"
