[package]
name = "bootloader_uefi"
version = "0.1.0"
authors = ["Jan Katzer <jan@katzer.dev>"]
edition = "2018"

[dependencies]
uefi = {version = "0.7.0", default-features = false, features = []}
atomic = "0.5.0"
elf_rs = "0.1.3"
